- id: fmt
  name: fmt
  description: Format Rust sources.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
  stages:
    - pre-commit
    - pre-merge-commit
    - manual

- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: env CARGO_CHECK=1 cargo check
  language: system
  types: [file]
  files: ^.*(Cargo\.toml|Cargo\.lock|.*\.rs)$
  pass_filenames: false
  stages:
    - pre-commit
    - pre-merge-commit
    - pre-push
    - manual

- id: clippy
  name: clippy
  description: Lint Rust sources
  entry: env CARGO_LINT=1 cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [file]
  files: ^.*(Cargo\.toml|Cargo\.lock|.*\.rs)$
  pass_filenames: false
  stages:
    - pre-commit
    - pre-merge-commit
    - pre-push
    - manual


